- name: Configure external zone in firewall
  hosts: "{{ hosts_inven }}"
  tasks:
    - name: firewall rule service http and https
      firewalld:
        service: "{{ item }}"
        permanent: yes
        immediate: yes
        state: enabled
      loop:
        - http
        - https

    - name: firewall rule port 80 and 443
      firewalld:
        port: "{{ item }}"
        permanent: yes
        immediate: yes
        state: enabled
      loop:
        - 80/tcp
        - 443/tcp